name: web1
channels:
  - defaults
  - conda-forge
dependencies:
  # Core Python and Environment
  - python=3.12
  - pip
  - gunicorn
  
  # System-level dependencies that Django/Pillow/Postgres often need
  - openssl
  - sqlite
  - pillow
  
  # Your Pip-installed Django Stack
  - pip:
      - django==6.0.1
      - whitenoise==6.8.2
      - djangorestframework==3.16.1
      - djangorestframework-simplejwt==5.5.1
      - django-cors-headers==4.9.0
      - psycopg2-binary==2.9.11
      - boto3==1.42.39
      - botocore==1.42.39
      - asgiref==3.11.0
      - pyjwt==2.11.0
      - python-dateutil==2.9.0.post0
      - sqlparse==0.5.5
      - urllib3==2.6.3
      - jmespath==1.1.0
      - s3transfer==0.16.0
      - six==1.17.0


